name: ${name}
version: ${version}
main: ${main}
load: STARTUP
authors: [cyberpwn, NextdoorPsycho]
website: volmit.com
description: More than a Dimenson!
commands:
  iris:
    aliases: [ir, irs]
api-version: ${apiversion}
hotload-dependencies: false