name: Spigot1.8.8 Autobuild

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - run: git clone https://github.com/PolyhedralDev/Terra
      - run: ./Terra/gradlew build
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Spigot1.8.8 自动构建"
          files: |
             *
