name: Autobuild

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      #- run: git clone https://github.com/PolyhedralDev/Terra
      - run: |
          cd Iris
          git config --global user.email "m17089494917@163.com"
          git config --global user.name "ObcbO"
          chmod +x gradlew
          ./gradlew build
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "自动构建"
          files: |
             *
